server:
  port: 8003

spring:
  mail:
    protocol: smtp #smtp是邮件发送协议，pop3和stmp是邮件接收协议。因为我们要发送邮件，因此是smtp
    host: smtp.qq.com #邮件发送服务器的主机，这里采用的是QQ邮箱来发送邮件
    port: 587 #邮件发送服务器的端口
    auth: true #一般情况下，发送邮件都是要进行验证
    username: 2352441187@qq.com #邮件发送服务器的用户名
    password: nmmhmcujxnqqecie #密码