server:
  # 服务端口
  port: 8081
  servlet:
    context-path: /

spring:
  profiles:
  #  active: '@activatedProperties@'
    active: pro
  devtools:
    livereload:
      enabled: true
      port: 35729
    restart:
      enabled: true


# swagger
swagger:
  version: 1.0
  groupName: 项目
  title: 项目名
  description: 接口文档
  #扫描目录
  basePackage: com.gyp.springboot.controller